name: Post-Update Commands

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - renovate/**
      - dependabot/**

permissions:
  contents: read

jobs:
  post-upgrade-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.11.0"

      - name: Run post-update commands
        run: |
          npm ci
          npx --workspace @yay-machine/site msw init
          npx @biomejs/biome migrate --write
          npm run fix

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Commit only if there are changes
          if ! git diff --quiet; then
            git commit -m "chore: run post-update tasks"
            git push
          else
            echo "No changes to commit"
          fi

      # - name: Push changes
      #   run: git push origin HEAD:${{ github.head_ref }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
