name: Post-Update Commands

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read

jobs:
  post-upgrade-commit:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.11.1"

      - name: Install dependencies
        run: |
          npm ci

      - name: Update MSW worker script
        run: |
          npx --workspace @yay-machine/site msw init

      - name: Migrate Biome config
        run: |
          npx @biomejs/biome migrate --write

      - name: Fix formatting
        run: |
          npm run fix

      - name: Print diffs
        run: |
          git diff

      - name: Commit and Push changes
        id: commit_and_push
        run: |
          # Commit only if there are changes
          if ! git diff --quiet; then
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: run post-update tasks"
            git push origin HEAD:${{ github.head_ref }}
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "committed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger build workflow
        if: steps.commit_and_push.outputs.committed == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: '${{ github.head_ref }}'
            })
