name: Renovate Post-Upgrade Init Commit

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - renovate/**

permissions:
  contents: read

jobs:
  post-upgrade-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout renovate branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.11.0"

      - name: Run post-update commands
        run: |
          npx --workspace @yay-machine/site msw init
          npx @biomejs/biome migrate --write
          npm run fix

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "chore: run post-update tasks"

      - name: Push changes
        run: git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
